### ISSUE TITLE
NVENC options not visible on laptop

### ISSUE THREAD

**Issue by ma16v3** [Vouk/voukoder#39] opened 2018-03-03 16:58 UTC
I have voukoder on my desktop and laptop. All options appear on the desktrop in Premiere, but only the libx264, libx265, and Apple ProRes options show up on my laptop. Could it be a specs issue with my GPU?

Laptop specs:

CPU: 4th gen Intel Core i7 at 3.20 Ghz 4-core/8-thread
GPU: Nvidia GeForce GTX 765m
Memory: 12GB DDR3
OS: Windows 10

Nvidia drivers and Premiere Pro both at most recent version on both my PC and Laptop. Why wouldn't my laptop have the NVENC options? Kepler supports NVENC right?

**Comment by Vouk** [comment] 2018-03-03 20:42
Theoretically h.264 should be available, yes. Voukoder tries to open all encoders on startup, but may file if no nvenc session is available. Did you close all other programs using nvenc?

Please update to Voukoder 0.6.3 and send me logfile in the %TMP% folder. There should be an error message.

More information: https://www.voukoder.org/article/5-frequently-asked-questions-faq/

**Comment by ma16v3** [comment] 2018-03-04 03:03
[voukoder.log](https://github.com/Vouk/voukoder/files/1778124/voukoder.log)

Had to use 0.6.2 to generate a log file, but here it is. As far as I can tell, there are no programs using encoders open besides Premiere.

**Comment by Vouk** [comment] 2018-03-04 06:34
[03-03-2018 10:00:32] Nvenc initialized successfully
[03-03-2018 10:00:32] 1 CUDA capable devices found
[03-03-2018 10:00:32] [ GPU #0 - < GeForce GTX 765M > has Compute SM 3.0 ]
[03-03-2018 10:00:32] OpenEncodeSessionEx failed: **unsupported device (2)**
[03-03-2018 10:00:32] **No NVENC capable devices found**
[03-03-2018 10:00:32] Nvenc unloaded

It seems your laptop GPU is not supported.

**Comment by ma16v3** [comment] 2018-03-04 20:09
I wonder why that might be, as the GTX 765m is a Kepler GPU, GK106 in fact. Kepler was the first architecture in which NVENC was implemented. Is it possible that the plugin may be looking for something more than general NVENC compatibility or possibly a later revision of NVENC? It would make more sense, if so.

https://en.wikipedia.org/wiki/Nvidia_NVENC#First_generation,_Kepler

**Comment by Vouk** [comment] 2018-03-04 20:37
I am using the FFMpeg implementation internally. Did you try using FFMpeg on the command line? Does it work for you?

**Comment by ma16v3** [comment] 2018-03-04 20:50
Yes, I can run ffmpeg in CLI.

**Comment by Vouk** [comment] 2018-03-05 05:25
Please try to encode a video with "h264_nvenc" on CLI. FFMpeg checks the support when opening the encoder.

**Comment by ma16v3** [comment] 2018-03-05 14:59
Just tried it and it is coming back as unsupported. That's disappointing since the documentation on NVENC implies that a GK106 would be compatible. I wonder what is missing? Oh well.

**Comment by Vouk** [comment] 2018-03-05 16:10
Maybe nvenc is available (you could test with other programs, i.e. OBS), but FFMpeg itself requires a later version. But as this is not a bug in Voukoder i would like to close this issue. We can still discuss this topic on the Voukoder forum if you like.

**Closed by Vouk** 2018-03-05 16:10 UTC

**Comment by ma16v3** [comment] 2018-03-06 18:24
I see, that makes more sense to me. At least my PC can use it. I appreciate the time you've taken on this and thanks for the excellent plugin(my main PC is chewing through exports with this).
